using Terminal.Gui;
using System.IO;
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TEXT_EDITOR
{
    public partial class MyView
    {

        public MyView()
        {
            //Window1.model
            InitializeComponent();
            button2.Clicked += () => {
                try
                {
                    using (StreamReader sr = new StreamReader(Convert.ToString(textField.Text)))
                    {
                        textView.Text = sr.ReadToEnd();
                    }
                }catch(Exception e) {
                    MessageBox.ErrorQuery("ERROR", "Failed to read file:\n"+Convert.ToString(e), "OK");
                }
            };
            button.Clicked += () =>
            {
                try
                {
                    using (StreamWriter sr = new StreamWriter(Convert.ToString(textField.Text)))
                    {
                        sr.Write(textView.Text);
                    }
                }
                catch (Exception e)
                {
                    MessageBox.ErrorQuery("ERROR", "Failed to save file:\n"+Convert.ToString(e), "OK");
                }
            };
        }
    }
}
