
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.22.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TEXT_EDITOR {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.Button button2;
        
        private Terminal.Gui.Button button3;
        
        private Terminal.Gui.Button button;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.TextField textField;
        
        private Terminal.Gui.TextView textView;
        
        private void InitializeComponent() {
            this.textView = new Terminal.Gui.TextView();
            this.textField = new Terminal.Gui.TextField();
            this.label = new Terminal.Gui.Label();
            this.button = new Terminal.Gui.Button();
            this.button3 = new Terminal.Gui.Button();
            this.button2 = new Terminal.Gui.Button();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "命令行字符界面文本编辑器By SYSTEM_Girl | 按下Ctrl+Q退出";
            this.button2.Width = 48;
            this.button2.Height = 1;
            this.button2.X = 1;
            this.button2.Y = 0;
            this.button2.Data = "button2";
            this.button2.Text = "                    Read                    ";
            this.button2.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button2.IsDefault = false;
            this.Add(this.button2);
            this.button3.Width = 20;
            this.button3.Height = 1;
            this.button3.X = 50;
            this.button3.Y = 0;
            this.button3.Data = "button3";
            this.button3.Text = "   SelectFile   ";
            this.button3.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button3.IsDefault = false;
            this.Add(this.button3);
            this.button.Width = 48;
            this.button.Height = 1;
            this.button.X = 70;
            this.button.Y = 0;
            this.button.Data = "button";
            this.button.Text = "                    Save                    ";
            this.button.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button.IsDefault = false;
            this.Add(this.button);
            this.label.Width = 4;
            this.label.Height = 1;
            this.label.X = 1;
            this.label.Y = 2;
            this.label.Data = "label";
            this.label.Text = "FilePath:";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
            this.textField.Width = 108;
            this.textField.Height = 1;
            this.textField.X = 10;
            this.textField.Y = 2;
            this.textField.Secret = false;
            this.textField.Data = "textField";
            this.textField.Text = "";
            this.textField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textField);
            this.textView.Width = 114514;
            this.textView.Height = 1919810;
            this.textView.X = 1;
            this.textView.Y = 4;
            this.textView.AllowsTab = true;
            this.textView.AllowsReturn = true;
            this.textView.WordWrap = false;
            this.textView.Data = "textView";
            this.textView.Text = "Please read file first";
            this.textView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textView);
        }
    }
}
